Repository spring-financial-group/Dockerfiles, pull requests merged in 2022-08, with the labels that each got.

#2 Move Dockerfiles to lighthouse
  .gitignore
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  README.md
  build_containers.sh
  push_containers.sh
  trivydb/Dockerfile
  trivydb/downloader.sh
Labels: size/M

#3 Push latest tag on release
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M

#4 chore: add cuda image for pytorch
  python38-torch-cuda/Dockerfile
Labels: size/S, lgtm, approved

#5 fix: add opencv lib to base python
  python38/Dockerfile
Labels: size/XS
