Repository spring-financial-group/Dockerfiles, pull requests merged in 2024-07, with the labels that each got.

#51 chore: nginx docker image
  .lighthouse/jenkins-x/nginx/pr.yaml
  .lighthouse/jenkins-x/nginx/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  nginx/Dockerfile
Labels: size/L, approved

#99 Chore/UI images
  .lighthouse/jenkins-x/node/pr.yaml
  .lighthouse/jenkins-x/node/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  nginx/Dockerfile
  nginx/conf/default
  nginx/conf/default.conf
  node/Dockerfile
Labels: size/L, approved

#102 feat: add github cli to container-tools
  container-tools/Dockerfile
Labels: approved, size/XS

#103 fix: frontend vulnerabilities
  OWNERS
  OWNERS_ALIASES
  nginx/Dockerfile
Labels: size/S, approved
