Repository spring-financial-group/Dockerfiles, pull requests merged in 2025-03, with the labels that each got.

#124 chore: add deployment tools to android dockerfile
  android/Dockerfile
Labels: size/S, approved

#125 fix: use pull through cache
  nginx/Dockerfile
  node/Dockerfile
  openjdk14/Dockerfile
  openjre11/Dockerfile
  python310-torch-cpu/Dockerfile
  python310-torch-cuda/Dockerfile
  python310/Dockerfile
  terra-test/Dockerfile
Labels: size/S, approved

#126 chore: add apt update to command
  android/Dockerfile
Labels: approved, size/XS

#127 chore: build android on same node image as angular projects
  android/Dockerfile
Labels: approved, size/XS

#128 feat: add .NET 8 integration tests Dockerfile
  .lighthouse/jenkins-x/net8-integration-tests/pr.yaml
  .lighthouse/jenkins-x/net8-integration-tests/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  net8-integration-tests/Dockerfile
Labels: size/L, approved
